#PBS -l walltime=00:10:00
#PBS -l nodes=2:ppn=2
#PBS -N p2p_pingpong
#PBS -q secondary
#PBS -j oe

module load mvapich2/2.3rc2-gcc-7.2.0

module list

# Change to the directory from which the batch job was submitted
cd /home/nbhat4/scratch/charm/verbs-linux-x86_64-smp-prod/examples/charm++/zerocopy/benchmarks/p2pPingpong

make

# Run the MPI code
#./charmrun +p2 ./megaZCPingpong 16 524288 1000 100 0 ++mpiexec > /home/nbhat4/scratch/results/p2p_pingpong_nonsmp_new
#./charmrun +p2 ./megaZCPingpong 1048576 33554432 1000 100 0 ++mpiexec >> /home/nbhat4/scratch/results/p2p_pingpong_nonsmp_new


./charmrun +p2 ./megaZCPingpong ++ppn 1 +pemap 0,2 +commap 1,3 ++mpiexec >> /home/nbhat4/scratch/results/p2p_pingpong_smp_new
